import { Product, Service, Category } from './types';

export const categories: Category[] = [
  {
    id: 'water-filters',
    name: 'Water Filters',
    icon: 'droplet',
    subCategories: [
      { id: 'whole-house', name: 'Whole House Filters' },
      { id: 'under-sink', name: 'Under Sink Filters' },
      { id: 'countertop', name: 'Countertop Filters' },
      { id: 'pitcher', name: 'Pitcher Filters' },
    ],
  },
  {
    id: 'filter-parts',
    name: 'Filter Parts',
    icon: 'cog',
    subCategories: [
      { id: 'cartridges', name: 'Replacement Cartridges' },
      { id: 'membranes', name: 'RO Membranes' },
      { id: 'housings', name: 'Filter Housings' },
      { id: 'fittings', name: 'Fittings & Connectors' },
    ],
  },
  {
    id: 'water-softeners',
    name: 'Water Softeners',
    icon: 'waves',
    subCategories: [
      { id: 'salt-based', name: 'Salt-Based Softeners' },
      { id: 'salt-free', name: 'Salt-Free Softeners' },
      { id: 'portable', name: 'Portable Softeners' },
    ],
  },
  {
    id: 'ro-systems',
    name: 'RO Systems',
    icon: 'filter',
    subCategories: [
      { id: '3-stage', name: '3-Stage Systems' },
      { id: '5-stage', name: '5-Stage Systems' },
      { id: '7-stage', name: '7-Stage Systems' },
      { id: 'commercial', name: 'Commercial RO' },
    ],
  },
  {
    id: 'accessories',
    name: 'Accessories',
    icon: 'wrench',
    subCategories: [
      { id: 'faucets', name: 'Water Filter Faucets' },
      { id: 'storage', name: 'Storage Tanks' },
      { id: 'pumps', name: 'Booster Pumps' },
      { id: 'tools', name: 'Installation Tools' },
    ],
  },
  {
    id: 'testing-kits',
    name: 'Testing Kits',
    icon: 'flask-conical',
    subCategories: [
      { id: 'water-test', name: 'Water Test Kits' },
      { id: 'tds-meters', name: 'TDS Meters' },
      { id: 'ph-meters', name: 'pH Meters' },
    ],
  },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'AquaPure Whole House Filter System',
    description: 'High-capacity whole house water filtration system with sediment and carbon filters. Removes chlorine, sediment, rust, and improves taste and odor.',
    price: 349.99,
    wholesalePrice: 279.99,
    category: 'water-filters',
    subCategory: 'whole-house',
    image: 'water filter system',
    inStock: true,
    brand: 'AquaPure',
    rating: 4.8,
    reviews: 156,
  },
  {
    id: '2',
    name: 'CrystalClear Under Sink Filter',
    description: '3-stage under sink filtration system. Easy installation, removes 99% of contaminants including lead, chlorine, and bacteria.',
    price: 189.99,
    wholesalePrice: 149.99,
    category: 'water-filters',
    subCategory: 'under-sink',
    image: 'under sink water filter',
    inStock: true,
    brand: 'CrystalClear',
    rating: 4.6,
    reviews: 203,
  },
  {
    id: '3',
    name: 'PureFlow Countertop Filter',
    description: 'Portable countertop water filter with advanced multi-stage filtration. No installation required.',
    price: 129.99,
    wholesalePrice: 99.99,
    category: 'water-filters',
    subCategory: 'countertop',
    image: 'countertop water filter',
    inStock: true,
    brand: 'PureFlow',
    rating: 4.5,
    reviews: 89,
  },
  {
    id: '4',
    name: 'AquaBrite Water Filter Pitcher',
    description: '10-cup capacity water filter pitcher with BPA-free materials. Filter lasts up to 2 months.',
    price: 39.99,
    wholesalePrice: 29.99,
    category: 'water-filters',
    subCategory: 'pitcher',
    image: 'water filter pitcher',
    inStock: true,
    brand: 'AquaBrite',
    rating: 4.3,
    reviews: 421,
  },
  {
    id: '5',
    name: 'Universal Replacement Cartridge 6-Pack',
    description: 'Compatible with most standard 10-inch filter housings. 5-micron sediment filters.',
    price: 45.99,
    wholesalePrice: 34.99,
    category: 'filter-parts',
    subCategory: 'cartridges',
    image: 'water filter cartridge',
    inStock: true,
    brand: 'FilterPro',
    rating: 4.7,
    reviews: 312,
  },
  {
    id: '6',
    name: 'Premium RO Membrane 75GPD',
    description: 'High-quality reverse osmosis membrane. 75 gallons per day capacity. Removes up to 99% of dissolved solids.',
    price: 79.99,
    wholesalePrice: 59.99,
    category: 'filter-parts',
    subCategory: 'membranes',
    image: 'ro membrane',
    inStock: true,
    brand: 'AquaTech',
    rating: 4.9,
    reviews: 178,
  },
  {
    id: '7',
    name: 'Clear Filter Housing 10-inch',
    description: 'Durable clear filter housing allows visual inspection. Includes mounting bracket and wrench.',
    price: 24.99,
    wholesalePrice: 18.99,
    category: 'filter-parts',
    subCategory: 'housings',
    image: 'filter housing',
    inStock: true,
    brand: 'AquaParts',
    rating: 4.4,
    reviews: 95,
  },
  {
    id: '8',
    name: 'Quick Connect Fittings Set',
    description: 'Complete set of push-to-connect fittings for 1/4" tubing. Includes elbows, tees, and straight connectors.',
    price: 16.99,
    wholesalePrice: 12.99,
    category: 'filter-parts',
    subCategory: 'fittings',
    image: 'water filter fittings',
    inStock: true,
    brand: 'ConnectPro',
    rating: 4.6,
    reviews: 267,
  },
  {
    id: '9',
    name: 'SmartSoft 48000 Grain Water Softener',
    description: 'Digital salt-based water softener for homes up to 6 people. Includes bypass valve and brine tank.',
    price: 599.99,
    wholesalePrice: 479.99,
    category: 'water-softeners',
    subCategory: 'salt-based',
    image: 'water softener',
    inStock: true,
    brand: 'SmartSoft',
    rating: 4.7,
    reviews: 134,
  },
  {
    id: '10',
    name: 'EcoSoft Salt-Free Conditioner',
    description: 'Environmentally friendly salt-free water conditioner. Prevents scale buildup without chemicals.',
    price: 449.99,
    wholesalePrice: 359.99,
    category: 'water-softeners',
    subCategory: 'salt-free',
    image: 'salt free water softener',
    inStock: true,
    brand: 'EcoSoft',
    rating: 4.4,
    reviews: 87,
  },
  {
    id: '11',
    name: 'TravelSoft Portable Softener',
    description: 'Compact portable water softener perfect for RVs and boats. 16000 grain capacity.',
    price: 189.99,
    wholesalePrice: 149.99,
    category: 'water-softeners',
    subCategory: 'portable',
    image: 'portable water softener',
    inStock: true,
    brand: 'TravelSoft',
    rating: 4.5,
    reviews: 62,
  },
  {
    id: '12',
    name: 'PureMax 3-Stage RO System',
    description: 'Compact 3-stage reverse osmosis system. Perfect for apartments and small spaces.',
    price: 199.99,
    wholesalePrice: 159.99,
    category: 'ro-systems',
    subCategory: '3-stage',
    image: '3 stage ro system',
    inStock: true,
    brand: 'PureMax',
    rating: 4.6,
    reviews: 145,
  },
  {
    id: '13',
    name: 'AquaElite 5-Stage RO System',
    description: 'Premium 5-stage reverse osmosis with remineralization. Includes storage tank and faucet.',
    price: 329.99,
    wholesalePrice: 259.99,
    category: 'ro-systems',
    subCategory: '5-stage',
    image: '5 stage ro system',
    inStock: true,
    brand: 'AquaElite',
    rating: 4.8,
    reviews: 289,
  },
  {
    id: '14',
    name: 'UltraPure 7-Stage Alkaline RO',
    description: 'Advanced 7-stage RO system with alkaline filter and UV sterilization. Premium quality water.',
    price: 499.99,
    wholesalePrice: 399.99,
    category: 'ro-systems',
    subCategory: '7-stage',
    image: '7 stage ro system',
    inStock: true,
    brand: 'UltraPure',
    rating: 4.9,
    reviews: 198,
  },
  {
    id: '15',
    name: 'CommercialPro 400GPD RO System',
    description: 'High-capacity commercial reverse osmosis system. 400 gallons per day for restaurants and offices.',
    price: 1299.99,
    wholesalePrice: 999.99,
    category: 'ro-systems',
    subCategory: 'commercial',
    image: 'commercial ro system',
    inStock: true,
    brand: 'CommercialPro',
    rating: 4.8,
    reviews: 76,
  },
  {
    id: '16',
    name: 'Chrome Water Filter Faucet',
    description: 'Designer chrome-finished water filter faucet. 360-degree swivel spout.',
    price: 49.99,
    wholesalePrice: 37.99,
    category: 'accessories',
    subCategory: 'faucets',
    image: 'water filter faucet',
    inStock: true,
    brand: 'FaucetPro',
    rating: 4.5,
    reviews: 112,
  },
  {
    id: '17',
    name: '4-Gallon Storage Tank',
    description: 'NSF certified pressurized water storage tank for RO systems. Pre-charged and ready to install.',
    price: 69.99,
    wholesalePrice: 52.99,
    category: 'accessories',
    subCategory: 'storage',
    image: 'water storage tank',
    inStock: true,
    brand: 'TankMaster',
    rating: 4.6,
    reviews: 143,
  },
  {
    id: '18',
    name: '100GPD Booster Pump',
    description: 'Quiet operation booster pump increases RO system efficiency. Automatic shut-off.',
    price: 89.99,
    wholesalePrice: 69.99,
    category: 'accessories',
    subCategory: 'pumps',
    image: 'water pump',
    inStock: true,
    brand: 'PumpTech',
    rating: 4.7,
    reviews: 98,
  },
  {
    id: '19',
    name: 'Professional Installation Tool Kit',
    description: 'Complete installation tool kit with tubing cutter, wrench, drill bits, and Teflon tape.',
    price: 34.99,
    wholesalePrice: 26.99,
    category: 'accessories',
    subCategory: 'tools',
    image: 'plumbing tools',
    inStock: true,
    brand: 'ToolPro',
    rating: 4.4,
    reviews: 156,
  },
  {
    id: '20',
    name: 'Complete Water Test Kit',
    description: 'Professional-grade water testing kit. Tests for 10 common contaminants including lead, bacteria, and chlorine.',
    price: 29.99,
    wholesalePrice: 22.99,
    category: 'testing-kits',
    subCategory: 'water-test',
    image: 'water test kit',
    inStock: true,
    brand: 'TestPro',
    rating: 4.6,
    reviews: 234,
  },
  {
    id: '21',
    name: 'Digital TDS Meter',
    description: 'Accurate digital TDS meter with LCD display. Measures water quality from 0-9990 ppm.',
    price: 19.99,
    wholesalePrice: 14.99,
    category: 'testing-kits',
    subCategory: 'tds-meters',
    image: 'tds meter',
    inStock: true,
    brand: 'AquaMeter',
    rating: 4.7,
    reviews: 312,
  },
  {
    id: '22',
    name: 'pH Meter with Calibration Solution',
    description: 'Portable pH meter with automatic temperature compensation. Includes calibration solutions.',
    price: 39.99,
    wholesalePrice: 29.99,
    category: 'testing-kits',
    subCategory: 'ph-meters',
    image: 'ph meter',
    inStock: true,
    brand: 'pHPro',
    rating: 4.5,
    reviews: 187,
  },
];

export const services: Service[] = [
  {
    id: 's1',
    name: 'Water Filter Installation',
    description: 'Professional installation of water filtration systems including whole house, under sink, and RO systems.',
    price: 149.99,
  },
  {
    id: 's2',
    name: 'Water Softener Installation',
    description: 'Complete installation service for water softening systems. Includes plumbing connections and system setup.',
    price: 249.99,
  },
  {
    id: 's3',
    name: 'Filter Replacement Service',
    description: 'Regular maintenance and filter replacement for all types of water filtration systems.',
    price: 79.99,
  },
  {
    id: 's4',
    name: 'Water Quality Testing',
    description: 'Comprehensive water quality analysis with detailed report and recommendations.',
    price: 99.99,
  },
  {
    id: 's5',
    name: 'System Maintenance',
    description: 'Annual maintenance service including filter replacement, sanitization, and performance check.',
    price: 129.99,
  },
  {
    id: 's6',
    name: 'Emergency Repair Service',
    description: 'Same-day repair service for leaking or malfunctioning water filtration systems.',
    price: 199.99,
  },
  {
    id: 's7',
    name: 'Water Pressure Optimization',
    description: 'Diagnosis and adjustment of water pressure issues. Includes booster pump installation if needed.',
    price: 179.99,
  },
  {
    id: 's8',
    name: 'Consultation & Design',
    description: 'Professional consultation for custom water treatment solutions. Includes water testing and system design.',
    price: 89.99,
  },
];
